const db = require("../index");
const subjectCategory = require("./modules/academics/subject/subjectCategory");
const subject = require("./modules/academics/subject/subject");
const subjectPrerequisite = require("./modules/academics/subject/subjectPrerequisite");
const college = require("./modules/academics/college");
const course = require("./modules/academics/course");
const designation = require("./modules/designation");
const profile = require("./modules/profile/profile");
const department = require("./modules/department");
const employee = require("./modules/employee");
const citizenship = require("./modules/profile/citizenship");
const benefit = require("./modules/profile/benefit");
const contact = require("./modules/profile/contact");
const address = require("./modules/profile/address");
const family = require("./modules/profile/family/family");
const child = require("./modules/profile/family/child");
const education = require("./modules/profile/experience/education");
const civilServiceEligibility = require("./modules/profile/experience/civilServiceEligibility");
const workExperience = require("./modules/profile/experience/workExperience");
const voluntaryWorkExperience = require("./modules/profile/experience/voluntaryWorkExperience");
const training = require("./modules/profile/experience/training");
const hobby = require("./modules/profile/hobby");
const recognition = require("./modules/profile/recognition");
const organization = require("./modules/profile/organization");
const reference = require("./modules/profile/reference");
const governmentIssueId = require("./modules/profile/governmentIssueId");
const photo = require("./modules/profile/photo");
const account = require("./modules/account");
const section = require("./modules/academics/section");
const departmentHead = require("./modules/departmentHead");
const personnelSchedule = require("./modules/personnelSchedule");
const semester = require("./modules/system-settings/semester");
const schoolYear = require("./modules/system-settings/schoolYear");

module.exports = async () => {
  let message = "";
  try {
    await db.executeQuery(subjectCategory);
    await db.executeQuery(subject);
    await db.executeQuery(subjectPrerequisite);
    await db.executeQuery(college);
    await db.executeQuery(course);
    await db.executeQuery(section);
    await db.executeQuery(department);
    await db.executeQuery(designation);
    await db.executeQuery(benefit);
    await db.executeQuery(contact);
    await db.executeQuery(address);
    await db.executeQuery(family);
    await db.executeQuery(child);
    await db.executeQuery(photo);
    await db.executeQuery(governmentIssueId);
    await db.executeQuery(account);
    await db.executeQuery(profile);
    await db.executeQuery(employee);
    await db.executeQuery(citizenship);
    await db.executeQuery(education);
    await db.executeQuery(education);
    await db.executeQuery(civilServiceEligibility);
    await db.executeQuery(workExperience);
    await db.executeQuery(voluntaryWorkExperience);
    await db.executeQuery(training);
    await db.executeQuery(hobby);
    await db.executeQuery(recognition);
    await db.executeQuery(organization);
    await db.executeQuery(reference);
    await db.executeQuery(departmentHead);
    await db.executeQuery(personnelSchedule);
    await db.executeQuery(semester);
    await db.executeQuery(schoolYear);
    message = "Database tables created.";
  } catch (errors) {
    console.log(errors);
  }
  return message;
};
