export const ACCOUNT_LOGIN = "ACCOUNT_LOGIN";
export const SET_ACCOUNT_ERROR = "SET_ACCOUNT_ERROR";
export const SET_ACCOUNT_AUTHENTICATION = "SET_ACCOUNT_AUTHENTICATION";
export const CHECK_ACCOUNT_AUTHENTICATION = "CHECK_ACCOUNT_AUTHENTICATION";
export const SET_PURGE_ACCOUNT_AUTHENTICATION =
  "SET_PURGE_ACCOUNT_AUTHENTICATION";
